# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/Project/Vivado/Signal_Generator/Signal_Generator.cache/wt [current_project]
set_property parent.project_path D:/FPGA/Project/Vivado/Signal_Generator/Signal_Generator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part sipeed.com:tang-hex:part0:1.0 [current_project]
set_property ip_output_repo d:/FPGA/Project/Vivado/Signal_Generator/Signal_Generator.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/FPGA/Project/Vivado/Signal_Generator/Signal_Generator.srcs/sources_1/new/Control.v
  D:/FPGA/Project/Vivado/Signal_Generator/Signal_Generator.srcs/sources_1/new/DAC7512.v
  D:/FPGA/Project/Vivado/Signal_Generator/Signal_Generator.srcs/sources_1/new/Encoder.v
  D:/FPGA/Project/Vivado/Signal_Generator/Signal_Generator.srcs/sources_1/new/Key.v
  D:/FPGA/Project/Vivado/Signal_Generator/Signal_Generator.srcs/sources_1/new/Synthesis.v
  D:/FPGA/Project/Vivado/Signal_Generator/Signal_Generator.srcs/sources_1/new/Signal_Generator.v
}
read_ip -quiet D:/FPGA/Project/Vivado/Signal_Generator/Signal_Generator.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/Project/Vivado/Signal_Generator/Signal_Generator.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Signal_Generator -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Signal_Generator.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Signal_Generator_utilization_synth.rpt -pb Signal_Generator_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
